alias git-track='function _gittrack(){ git branch --set-upstream-to=origin/"$1" "$1";};_gittrack'
alias eft='ember exam --split=2 --parallel --silent'
alias pg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias esw='ember s --watch=polling'
alias etw='ember t --watch=polling'
